### ISSUE TITLE
I don't understand how to run it??

### ISSUE THREAD

**Issue by feedmewifi** [sealemar/BingRewards#133] opened 2015-04-28 20:26 UTC
Obviously there's a way, but I can't figure it out. Under "Running the script" is says to go to the directory and run it, but with what program? Windows cmd doesn't understand the "python" in front of it, and I tried using python command line and it doesn't even recognize cd as a command, so I'm guessing it's not that.
Help please!

**Comment by feedmewifi** [comment] 2015-04-28 20:28
also: if I say just main.py in windows cmd while in the right directory, it says missing parenthesis

**Comment by amayer5125** [comment] 2015-04-28 20:29
@feedmewifi do you have python installed on your Windows computer?

**Comment by feedmewifi** [comment] 2015-04-28 20:32
yeah

**Comment by amayer5125** [comment] 2015-04-28 20:35
can you try
`cd C:\path\to\bingrewards`
`pything.exe main.py`
(I dont have Windows so this is an adventure for both of us)

**Comment by feedmewifi** [comment] 2015-04-28 20:39
![image](https://cloud.githubusercontent.com/assets/12159515/7379760/0fab018c-edc5-11e4-99f7-f3da1aa95b0e.png)
no luck

**Comment by PlasmaPower** [comment] 2015-04-28 20:42
I think the problem is that python is not in your path. Do you know where `python.exe` is? Along with @amayer5125 I don't have a windows installation currently, so IDK where the default location is. You could try searching your hard disk with Windows Explorer, or you could try looking `python.exe` in `C:\Python`, `C:\Program Files\Python`, or `C:\Program Files (x86)\Python`.

**Comment by feedmewifi** [comment] 2015-04-28 20:44
it's in the default C:\Program Files (x86)\Python location, as far as I know. Should I move bing-rewards into it? Should I move it into bing-rewards?

**Comment by amayer5125** [comment] 2015-04-28 20:46
you may need to do something like
`C:\Program Files (x86)\Python\python.exe C:\path\to\bingrewards\main.py`
Im not sure if you need to escape the python path somehow? Or maybe put quotes around it?

**Comment by feedmewifi** [comment] 2015-04-28 20:50
>Microsoft Windows [Version 6.1.7601]
>Copyright (c) 2009 Microsoft Corporation.  All rights reserved.
>
>C:\Users\Helmut>C:\Python34\python.exe C:\Users\Helmut\Desktop\BingRewards-maste
>r\main.py
>  File "C:\Users\Helmut\Desktop\BingRewards-master\main.py", line 64
>    print "-" * 80
>            ^
>SyntaxError: Missing parentheses in call to 'print'
>
>C:\Users\Helmut>

**Comment by amayer5125** [comment] 2015-04-28 20:51
What version of python are you running?

**Comment by PlasmaPower** [comment] 2015-04-28 20:51
@feedmewifi You are really close, you just need to install python 2 instead of 3, then substitute `Python34` for something like `Python25`.

**Comment by feedmewifi** [comment] 2015-04-28 20:52
I thought it said python 2.5+ or something like that?

**Comment by amayer5125** [comment] 2015-04-28 20:53
2.7+ but you still need to use version 2 of python... I guess we should update to say we only support version 2.

**Comment by feedmewifi** [comment] 2015-04-28 21:08
Thanks for you help! Got it to run, but now I've got a different set of problems. 

>ConfigError: Corresponding account is not found for EVENTS.ACCOUNT.ref = [(my email)@gmail.com]

**Comment by amayer5125** [comment] 2015-04-28 21:08
You need to comment out the events section of the xml if you are not using it.

**Comment by feedmewifi** [comment] 2015-04-28 21:12
Making progress!
This is what it's saying and I can't even understand what it mean or what's wrong

>C:\Users\Helmut>C:\Python27\python.exe C:\Users\Helmut\Desktop\BingRewards-maste
r\main.py
>2015-04-28 17:09:45.3 - script started
--------------------------------------------------------------------------------


>Live - helmutisgreat@gmail.com
Result 1/11:
-----------
name        : Get all the perks
url         : http://www.bing.com/rewardsapp/redirect?url=%2frewards%2flevels&id
=a2512127&hash=413b7bda14bb9eb2bbfad5b84d5751a4&state=Active&rcid=0&aid=urlrewar
d&bruid=516569A1-CFFA-4D43-B03B-837263EA194C&ml=ExpandedWebLayout&rh=
description : Set your sights on Gold status and see your perks multiply.
   Error    :   true
   Message  : Didn't earn any points for click
   Action   : warn

>Result 2/11:
-----------
name        : Trivia challenge
url         : http://www.bing.com/search?q=NFL+Draft&raid=quiz&rnoreward=1&roid=
quiz_MQ_8
progressCur : 0
progressMax : 3
progress %  : 0.00%
description : Earn a credit for each correct answer. Don't know it? Search for i
t!
   Error    :   true
   Message  : Didn't earn any points for click
   Action   : warn


>Live - helmutisgreat@gmail.com

>Points before:       468
Points after:        469
Points earned:         1
Lifetime Credits:    489

--------------------------------------------------------------------------------

**Comment by amayer5125** [comment] 2015-04-28 21:16
Some extra rewards cant be earned through our script. Trivia Challenge for instance requires human interaction to earn the reward.
As long as the script is running and doing searches you should be good.

**Comment by PlasmaPower** [comment] 2015-04-28 22:14
If you don't have any other problems, you can close the issue.

**Comment by feedmewifi** [comment] 2015-04-29 00:51
okay, now something has gone completly wrong. I know y'all aren't the ones to ask but I figure you might now something: my python.exe in python27 or whatever is 0 kb and when I try and launch it windows says"python.exe is not a valid win32 application." ????

**Comment by PlasmaPower** [comment] 2015-04-29 01:08
@feedmewifi Try reinstalling python maybe?

**Comment by feedmewifi** [comment] 2015-04-29 21:01
I tried launching the installer and clicking repair, but it didn't do anything. So, I guess I'll uninstall and then reinstall and see if it fixes anything.

**Closed** 2015-04-29 21:19 UTC
