### ISSUE TITLE
Account "Banned"

### ISSUE THREAD

**Issue by Binguu** [sealemar/BingRewards#139] opened 2015-05-25 00:24 UTC
![](http://i.gyazo.com/739e8b1997269bdcba398608daec6f55.png)

When running the script, some of my accounts will say they are temporarily banned or permanently banned, but when I go onto the actual bing website I can still login. Also, I can continue to earn points manually and through browser based bots. The accounts were at one point temporarily banned, so I'm not sure if that sets them as not usable forever, but I would like to get these accounts back to earning points ASAP.

Edit: I think the point of this is being missed. THESE ACCOUNTS ARE NOT ACTUALLY BANNED. I can still fully use them manually, it is only THE PROGRAM that THINKS they are banned. Using caps for important words.

**Comment by martinsbreno** [comment] 2015-05-25 02:06
Some of my account got banned too after I started to use this script. I have redeemed some gift cards before.

**Comment by Gishi1** [comment] 2015-05-25 09:07
id assume that accounts are getting banned because of the new Trivia challenge introduced a few months back. i think this wont affect me mainly because i only use one account and i do them by hand.

**Comment by diwu1989** [comment] 2015-05-25 19:00
I think a true browser based approach would be more reliable in the long run because Bing can introduce simple Javascript tests to verify whether you are just hitting URLs or actually using a real browser.

**Comment by Gishi1** [comment] 2015-05-26 03:33
thats true as well but i use a modded justinxxvii/bing bot that uses selenium and phantomjs.

**Comment by WolfEdge** [comment] 2015-05-26 15:47
I had the issue. Iirc it was because of the proxy I was using. If you want to use a proxy or something, you gotta login to the Bing Rewards site on browser using that proxy, so Bing can see it as 'authorised' or whatever. I reckon the script thinking you're 'banned' is a misinterpretation.

**Comment by Binguu** [comment] 2015-05-28 18:06
I don't use a proxy

**Comment by amayer5125** [comment] 2015-06-17 12:57
There was an issue where you need to agree to the Terms Of Use and BingRewards would incorrectly say your account has a temporary ban. I have since added a check #146 to see if you need to agree to TOU.

**Comment by amayer5125** [comment] 2015-06-22 13:25
@Binguu Have you tried the latest version to see if the problem is fixed?

**Comment by Binguu** [comment] 2015-06-26 22:52
Unfortunately I wasn't careful enough and the accounts were banned. Thought, they were not temporarily banned at this time, but they have since been banned before the fix.

**Comment by amayer5125** [comment] 2015-07-21 13:06
@Binguu if this is no longer a problem can you please close this issue?

**Comment by Binguu** [comment] 2015-07-23 06:36
It's not necessarily solved, but I will close it I guess.

**Closed** 2015-07-23 06:36 UTC

**Comment by amayer5125** [comment] 2015-07-23 13:38
@Binguu aside from your banned accounts did you try the latest version with non-banned accounts? I believe a patch I made fixed the mislabeled "temporary ban".

**Comment by Binguu** [comment] 2015-07-30 06:34
Unfortunately at this point all but one of my accounts have been banned, and the one remaining was never under the temp ban issue.

**Comment by MichaelChirico** [comment] 2016-01-28 15:59
Just hit this temporary ban thing myself.

Can reap points from the website searches, but the script fails with the error:

> Temporary account ban: User was not successfully signed in.

**Comment by amayer5125** [comment] 2016-01-28 16:11
@MichaelChirico are you running the newest version of the scirpt? This error was fixed a couple days ago.

**Comment by MichaelChirico** [comment] 2016-01-28 16:30
@amayer5125 Indeed I'm not. Would you mind linking the relevant commit?
