### ISSUE TITLE
Script start fails, empty log

### ISSUE THREAD

**Issue by LxanderUA** [sealemar/BingRewards#326] opened 2018-01-25 09:24 UTC
Just receive this:
```
2018-01-25 09:14:14.7 - script started
--------------------------------------------------------------------------------
For: Live - XXXXXX@XXXX
--------------------------------------------------------------------------------
Full log:
---------
Empty log
onScriptFailure: -mail
```
Error on both accounts.
For about month all was ok.
Login in account by PC work well.
How I can see what type of error happens?

**Comment by DimaRazb** [comment] 2018-01-25 09:34
The same from monday

**Comment by kaoticfen** [comment] 2018-01-25 12:07
Yeah im getting the same error.

**Comment by baltimoron** [comment] 2018-01-25 12:30
The problem is the "Donate points" rewards. For the old dashboard the script uses the word "points" to determine whether to hit (it's clunky but I never got around to fixing after they converted to the new dash). If the button text sees the word "points" it assumes that the previous word is numeric and tries to convert it, this is where it's crashing.

**Comment by baltimoron** [comment] 2018-01-25 12:50
fixed in latest commit

**Comment by kaoticfen** [comment] 2018-01-25 19:39
sorry for the ignorance but if the latest commit fixed it, is the fix in the master then?

**Comment by baltimoron** [comment] 2018-01-25 19:43
No just my fork. Going to try to get it merged with master this weekend.

**Comment by kaoticfen** [comment] 2018-01-25 19:48
gotcha. Thanks baltimoron.

**Comment by specu** [comment] 2018-01-25 19:53
@amayer5125 could we please get @baltimoron added to the developers of this project project (if he's ok with it)? I think right now the only way to get a working copy of this project is to use his fork.

**Closed** 2018-01-29 13:14 UTC
